### ISSUE TITLE
[Jekyll] Support multiple languages

### ISSUE THREAD

**Issue by JeffGuKang** [JeffGuKang/react-native-tutorial#27]
Consider to use Jekyll plugin for multiple languages.
There is two ways to use GitHub hosting.

## Use another repository for GitHub hosting with external plugin 

It looks to use the external plugin not supported by GitHub as https://stackoverflow.com/a/28252200./515932

Candidate

- https://github.com/kurtsson/jekyll-multiple-languages-plugin
- https://github.com/untra/polyglot

## Custom Jekyll files

https://github.com/sylvaindurand/jekyll-multilingual

**Comment by JeffGuKang** [comment]
First support languages would be English and Korean on this repository. 
Using Jekyll plugin for multi language support will be applied later.

**Comment by shushugah** [comment]
Greetings, I am a maintainer of https://github.com/kurtsson/jekyll-multiple-languages-plugin and would be happy to answer any questions you may have!

**Comment by JeffGuKang** [comment]
Hello @shushugah . Thanks for the great plugin. I am considering to use this cool plugin for multi language in the future. And it looks I need to create another GitHub repository for Jekyll hosting only to use plugins are not supported in GitHub as [jekyll multiple languages plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin). :) Is it common to use some GitHub repository like it?

**Comment by shushugah** [comment]
You can have a dedicated branch in the same repository for that purpose. In one repository I have, whenever a merge to master is made, it builds the `_site` to `release` and then GitHub only uploads the statically built content. 

The `.travis.yml` looks like this

```
language: ruby
cache: bundler
branches:
  only:
  - release
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release
```

It involves a few more configuration, can share the blog post I found. Otherwise you could use a service provider that doesn’t run builds in `Jekyll build —safe` mode which is what disables unapproved jekyll plug-ins
